// 4-star character icons

import Arlan from "./4stars/arlan/Character_Arlan_Icon.webp";
import Asta from "./4stars/asta/Character_Asta_Icon.webp";
import Danheng from "./4stars/danheng/Character_Dan_Heng_Icon.webp";
import Guinaifen from "./4stars/guinaifen/Character_Guinaifen_Icon.webp";
import Hanya from "./4stars/hanya/Character_Hanya_Icon.webp";
import Herta from "./4stars/herta/Character_Herta_Icon.webp";
import Hook from "./4stars/hook/Character_Hook_Icon.webp";
import Luka from "./4stars/luka/Character_Luka_Icon.webp";
import Lynx from "./4stars/lynx/Character_Lynx_Icon.webp";
import March7th from "./4stars/march7th/Character_March_7th_Icon.webp";
import Natasha from "./4stars/natasha/Character_Natasha_Icon.webp";
import Pela from "./4stars/pela/Character_Pela_Icon.webp";
import Qingque from "./4stars/qingque/Character_Qingque_Icon.webp";
import Sampo from "./4stars/sampo/Character_Sampo_Icon.webp";
import Serval from "./4stars/serval/Character_Serval_Icon.webp";
import Sushang from "./4stars/sushang/Character_Sushang_Icon.webp";
import Tingyun from "./4stars/tingyun/Character_Tingyun_Icon.webp";
import Yukong from "./4stars/yukong/Character_Yukong_Icon.webp";

// 5-star character icons

import Argenti from "./5stars/argenti/Character_Argenti_Icon.webp";
import Bailu from "./5stars/bailu/Character_Bailu_Icon.webp";
import Blade from "./5stars/blade/Character_Blade_Icon.webp";
import Bronya from "./5stars/bronya/Character_Bronya_Icon.webp";
import Clara from "./5stars/clara/Character_Clara_Icon.webp";
import Fuxuan from "./5stars/fuxuan/Character_Fu_Xuan_Icon.webp";
import Gepard from "./5stars/gepard/Character_Gepard_Icon.webp";
import Himeko from "./5stars/himeko/Character_Himeko_Icon.webp";
import Huohuo from "./5stars/huohuo/Character_Huo_Huo_Icon.webp";
import Imbibitorlunae from "./5stars/imbibitorlunae/Character_Imbibitor_Lunae_Icon.webp";
import Jingliu from "./5stars/jingliu/Character_Jingliu_Icon.webp";
import Jingyuan from "./5stars/jingyuan/Character_Jing_Yuan_Icon.webp";
import Kafka from "./5stars/kafka/Character_Kafka_Icon.webp";
import Luocha from "./5stars/luocha/Character_Luocha_Icon.webp";
import Seele from "./5stars/seele/Character_Seele_Icon.webp";
import Silverwolf from "./5stars/silverwolf/Character_Silver_Wolf_Icon.webp";
import Topaz from "./5stars/topaz/Character_Topaz_Icon.webp";
import FMCDestruction from "./5stars/trailblazer/female/physical/Character_Trailblazer_Female_Destruction_Icon.webp";
import MMCPreservation from "./5stars/trailblazer/male/fire/Character_Trailblazer_Male_Preservation_Icon.webp";
import Welt from "./5stars/welt/Character_Welt_Icon.webp";
import Yanqing from "./5stars/yanqing/Character_Yanqing_Icon.webp";

// character type icons

import Fire from "../types/Class_Type_Fire.webp";
import Ice from "../types/Class_Type_Ice.webp";
import Imaginary from "../types/Class_Type_Imaginary.webp";
import Lightning from "../types/Class_Type_Lightning.webp";
import Physical from "../types/Class_Type_Physical.webp";
import Quantum from "../types/Class_Type_Quantum.webp";
import Wind from "../types/Class_Type_Wind.webp";

// character path icons

import Abundance from "../paths/Character_Path_Abundance.webp";
import Destruction from "../paths/Character_Path_Destruction.webp";
import Erudition from "../paths/Character_Path_Erudition.webp";
import Harmony from "../paths/Character_Path_Harmony.webp";
import Hunt from "../paths/Character_Path_Hunt.webp";
import Nihility from "../paths/Character_Path_Nihility.webp";
import Preservation from "../paths/Character_Path_Preservation.webp";

export const characters = [
  {
    name: "Arlan",
    rarity: 4,
    id: 1,
    type: "Lightning",
    path: "Destruction",
    icon: Arlan,
    iconType: Lightning,
    iconPath: Destruction,
    alt: "Character_Arlan_Icon",
    altType: "Class_Type_Lightning",
    altPath: "Character_Path_Destruction",
  },
  {
    name: "Asta",
    rarity: 4,
    id: 2,
    type: "Fire",
    path: "Harmony",
    icon: Asta,
    iconType: Fire,
    iconPath: Harmony,
    alt: "Character_Asta_Icon",
    altType: "Class_Type_Fire",
    altPath: "Character_Path_Harmony",
  },
  {
    name: "Dan Heng",
    rarity: 4,
    id: 3,
    type: "Wind",
    path: "Hunt",
    icon: Danheng,
    iconType: Wind,
    iconPath: Hunt,
    alt: "Character_Danheng_Icon",
    altType: "Class_Type_Wind",
    altPath: "Character_Path_Hunt",
  },
  {
    name: "Guinaifen",
    rarity: 4,
    id: 4,
    type: "Fire",
    path: "Nihility",
    icon: Guinaifen,
    iconType: Fire,
    iconPath: Nihility,
    alt: "Character_Guinaifen_Icon",
    altType: "Class_Type_Fire",
    altPath: "Character_Path_Nihility",
  },
  {
    name: "Hanya",
    rarity: 4,
    id: 5,
    type: "Physical",
    path: "Harmony",
    icon: Hanya,
    iconType: Physical,
    iconPath: Harmony,
    alt: "Character_Hanya_Icon",
    altType: "Class_Type_Physical",
    altPath: "Character_Path_Harmony",
  },
  {
    name: "Herta",
    rarity: 4,
    id: 6,
    type: "Ice",
    path: "Erudition",
    icon: Herta,
    iconType: Ice,
    iconPath: Erudition,
    alt: "Character_Herta_Icon",
    altType: "Class_Type_Ice",
    altPath: "Character_Path_Erudition",
  },
  {
    name: "Hook",
    rarity: 4,
    id: 7,
    type: "Fire",
    path: "Destruction",
    icon: Hook,
    iconType: Fire,
    iconPath: Destruction,
    alt: "Character_Hook_Icon",
    altType: "Class_Type_Fire",
    altPath: "Character_Path_Destruction",
  },
  {
    name: "Luka",
    rarity: 4,
    id: 8,
    type: "Physical",
    path: "Nihility",
    icon: Luka,
    iconType: Physical,
    iconPath: Nihility,
    alt: "Character_Luka_Icon",
    altType: "Class_Type_Physical",
    altPath: "Character_Path_Nihility",
  },
  {
    name: "Lynx",
    rarity: 4,
    id: 9,
    type: "Quantum",
    path: "Abundance",
    icon: Lynx,
    iconType: Quantum,
    iconPath: Abundance,
    alt: "Character_Lynx_Icon",
    altType: "Class_Type_Quantum",
    altPath: "Character_Path_Abundance",
  },
  {
    name: "March 7th",
    rarity: 4,
    id: 10,
    type: "Ice",
    path: "Preservation",
    icon: March7th,
    iconType: Ice,
    iconPath: Preservation,
    alt: "Character_March_7th_Icon",
    altType: "Class_Type_Ice",
    altPath: "Character_Path_Preservation",
  },
  {
    name: "Natasha",
    rarity: 4,
    id: 11,
    type: "Physical",
    path: "Abundance",
    icon: Natasha,
    iconType: Physical,
    iconPath: Abundance,
    alt: "Character_Natasha_Icon",
    altType: "Class_Type_Physical",
    altPath: "Character_Path_Abundance",
  },
  {
    name: "Pela",
    rarity: 4,
    id: 12,
    type: "Ice",
    path: "Nihility",
    icon: Pela,
    iconType: Ice,
    iconPath: Nihility,
    alt: "Character_Pela_Icon",
    altType: "Class_Type_Ice",
    altPath: "Character_Path_Nihility",
  },
  {
    name: "Qingque",
    rarity: 4,
    id: 13,
    type: "Quantum",
    path: "Erudition",
    icon: Qingque,
    iconType: Quantum,
    iconPath: Erudition,
    alt: "Character_Qingque_Icon",
    altType: "Class_Type_Quantum",
    altPath: "Character_Path_Erudition",
  },
  {
    name: "Sampo",
    rarity: 4,
    id: 14,
    type: "Wind",
    path: "Nihility",
    icon: Sampo,
    iconType: Wind,
    iconPath: Nihility,
    alt: "Character_Sampo_Icon",
    altType: "Class_Type_Wind",
    altPath: "Character_Path_Nihility",
  },
  {
    name: "Serval",
    rarity: 4,
    id: 15,
    type: "Lightning",
    path: "Erudition",
    icon: Serval,
    iconType: Lightning,
    iconPath: Erudition,
    alt: "Character_Serval_Icon",
    altType: "Class_Type_Lightning",
    altPath: "Character_Path_Erudition",
  },
  {
    name: "Sushang",
    rarity: 4,
    id: 16,
    type: "Physical",
    path: "Hunt",
    icon: Sushang,
    iconType: Physical,
    iconPath: Hunt,
    alt: "Character_Sushang_Icon",
    altType: "Class_Type_Physical",
    altPath: "Character_Path_Hunt",
  },
  {
    name: "Tingyun",
    rarity: 4,
    id: 17,
    type: "Lightning",
    path: "Harmony",
    icon: Tingyun,
    iconType: Lightning,
    iconPath: Harmony,
    alt: "Character_Tingyun_Icon",
    altType: "Class_Type_Lightning",
    altPath: "Character_Path_Harmony",
  },
  {
    name: "Yukong",
    rarity: 4,
    id: 18,
    type: "Imaginary",
    path: "Harmony",
    icon: Yukong,
    iconType: Imaginary,
    iconPath: Harmony,
    alt: "Character_Yukong_Icon",
    altType: "Class_Type_Imaginary",
    altPath: "Character_Path_Harmony",
  },
  {
    name: "Bailu",
    rarity: 5,
    id: 19,
    type: "Lightning",
    path: "Abundance",
    icon: Bailu,
    iconType: Lightning,
    iconPath: Abundance,
    alt: "Character_Bailu_Icon",
    altType: "Class_Type_Lightning",
    altPath: "Character_Path_Abundance",
  },
  {
    name: "Blade",
    rarity: 5,
    id: 20,
    type: "Wind",
    path: "Destruction",
    icon: Blade,
    iconType: Wind,
    iconPath: Destruction,
    alt: "Character_Blade_Icon",
    altType: "Class_Type_Wind",
    altPath: "Character_Path_Destruction",
  },
  {
    name: "Bronya",
    rarity: 5,
    id: 21,
    type: "Wind",
    path: "Harmony",
    icon: Bronya,
    iconType: Wind,
    iconPath: Harmony,
    alt: "Character_Bronya_Icon",
    altType: "Class_Type_Wind",
    altPath: "Character_Path_Harmony",
  },
  {
    name: "Clara",
    rarity: 5,
    id: 22,
    type: "Physical",
    path: "Destruction",
    icon: Clara,
    iconType: Physical,
    iconPath: Destruction,
    alt: "Character_Clara_Icon",
    altType: "Class_Type_Physical",
    altPath: "Character_Path_Destruction",
  },
  {
    name: "Fu Xuan",
    rarity: 5,
    id: 23,
    type: "Quantum",
    path: "Preservation",
    icon: Fuxuan,
    iconType: Quantum,
    iconPath: Preservation,
    alt: "Character_Fu_Xuan_Icon",
    altType: "Class_Type_Quantum",
    altPath: "Character_Path_Preservation",
  },
  {
    name: "Gepard",
    rarity: 5,
    id: 24,
    type: "Ice",
    path: "Preservation",
    icon: Gepard,
    iconType: Ice,
    iconPath: Preservation,
    alt: "Character_Gepard_Icon",
    altType: "Class_Type_Ice",
    altPath: "Character_Path_Preservation",
  },
  {
    name: "Himeko",
    rarity: 5,
    id: 25,
    type: "Fire",
    path: "Erudition",
    icon: Himeko,
    iconType: Fire,
    iconPath: Erudition,
    alt: "Character_Himeko_Icon",
    altType: "Class_Type_Fire",
    altPath: "Character_Path_Erudition",
  },
  {
    name: "Dan Heng • Imbibitor Lunae",
    rarity: 5,
    id: 26,
    type: "Imaginary",
    path: "Destruction",
    icon: Imbibitorlunae,
    iconType: Imaginary,
    iconPath: Destruction,
    alt: "Character_Imbibitor_Lunae_Icon",
    altType: "Class_Type_Imaginary",
    altPath: "Character_Path_Destruction",
  },
  {
    name: "Jingliu",
    rarity: 5,
    id: 27,
    type: "Ice",
    path: "Destruction",
    icon: Jingliu,
    iconType: Ice,
    iconPath: Destruction,
    alt: "Character_Jingliu_Icon",
    altType: "Class_Type_Ice",
    altPath: "Character_Path_Destruction",
  },
  {
    name: "Jing Yuan",
    rarity: 5,
    id: 28,
    type: "Lightning",
    path: "Erudition",
    icon: Jingyuan,
    iconType: Lightning,
    iconPath: Erudition,
    alt: "Character_Jing_Yuan_Icon",
    altType: "Class_Type_Lightning",
    altPath: "Character_Path_Erudition",
  },
  {
    name: "Kafka",
    rarity: 5,
    id: 29,
    type: "Lightning",
    path: "Nihility",
    icon: Kafka,
    iconType: Lightning,
    iconPath: Nihility,
    alt: "Character_Luocha_Icon",
    altType: "Class_Type_Lightning",
    altPath: "Character_Path_Nihility",
  },
  {
    name: "Luocha",
    rarity: 5,
    id: 30,
    type: "Imaginary",
    path: "Abundance",
    icon: Luocha,
    iconType: Imaginary,
    iconPath: Abundance,
    alt: "Character_Luocha_Icon",
    altType: "Class_Type_Imaginary",
    altPath: "Character_Path_Abundance",
  },
  {
    name: "Seele",
    rarity: 5,
    id: 31,
    type: "Quantum",
    path: "Hunt",
    icon: Seele,
    iconType: Quantum,
    iconPath: Hunt,
    alt: "Character_Seele_Icon",
    altType: "Class_Type_Quantum",
    altPath: "Character_Path_Hunt",
  },
  {
    name: "Silver Wolf",
    rarity: 5,
    id: 32,
    type: "Quantum",
    path: "Nihility",
    icon: Silverwolf,
    iconType: Quantum,
    iconPath: Nihility,
    alt: "Character_Silver_Wolf_Icon",
    altType: "Class_Type_Quantum",
    altPath: "Character_Path_Nihility",
  },
  {
    name: "Topaz and Numby",
    rarity: 5,
    id: 33,
    type: "Fire",
    path: "Hunt",
    icon: Topaz,
    iconType: Fire,
    iconPath: Hunt,
    alt: "Character_Topaz_Icon",
    altType: "Class_Type_Fire",
    altPath: "Character_Path_Hunt",
  },
  {
    name: "Trailblazer (Physical)",
    rarity: 5,
    id: 34,
    type: "Physical",
    path: "Destruction",
    icon: FMCDestruction,
    iconType: Physical,
    iconPath: Destruction,
    alt: "Character_Trailblazer_Female_Destruction_Icon",
    altType: "Class_Type_Physical",
    altPath: "Character_Path_Destruction",
  },
  {
    name: "Trailblazer (Fire)",
    rarity: 5,
    id: 35,
    type: "Fire",
    path: "Preservation",
    icon: MMCPreservation,
    iconType: Fire,
    iconPath: Preservation,
    alt: "Character_Trailblazer_Male_Preservation_Icon",
    altType: "Class_Type_Fire",
    altPath: "Character_Path_Preservation",
  },
  {
    name: "Welt",
    rarity: 5,
    id: 36,
    type: "Imaginary",
    path: "Nihility",
    icon: Welt,
    iconType: Imaginary,
    iconPath: Nihility,
    alt: "Character_Welt_Icon",
    altType: "Class_Type_Imaginary",
    altPath: "Character_Path_Nihility",
  },
  {
    name: "Yanqing",
    rarity: 5,
    id: 37,
    type: "Ice",
    path: "Hunt",
    icon: Yanqing,
    iconType: Ice,
    iconPath: Hunt,
    alt: "Character_Yanqing_Icon",
    altType: "Class_Type_Ice",
    altPath: "Character_Path_Hunt",
  },
  {
    name: "Huo Huo",
    rarity: 5,
    id: 38,
    type: "Wind",
    path: "Abundance",
    icon: Huohuo,
    iconType: Wind,
    iconPath: Abundance,
    alt: "Character_Huo_Huo_Icon",
    altType: "Class_Type_Wind",
    altPath: "Character_Path_Abundance",
  },
  {
    name: "Argenti",
    rarity: 5,
    id: 39,
    type: "Physical",
    path: "Erudition",
    icon: Argenti,
    iconType: Physical,
    iconPath: Erudition,
    alt: "Character_Argenti_Icon",
    altType: "Class_Type_Physical",
    altPath: "Character_Path_Erudition",
  },
];
